SET MODE MYSQL;
INSERT IGNORE INTO USERINFO (USERID, NAME, PASSWORD) VALUES ('admin', 'admin', 'admin');
INSERT IGNORE INTO USERINFO (USERID, NAME, PASSWORD) VALUES ('user', 'user', 'password');

/* Add few roles */
INSERT IGNORE INTO USERROLES (ROLEID, ROLE_NAME) VALUES ('ADMIN', 'ROLE_ADMIN');
INSERT IGNORE INTO USERROLES (ROLEID, ROLE_NAME) VALUES ('USER', 'ROLE_USER');
INSERT IGNORE INTO USERROLES (ROLEID, ROLE_NAME) VALUES ('GUEST', 'ROLE_GUEST');

/* Add few mapping */
INSERT IGNORE INTO ROLE_MAPPING (USERID, ROLEID) VALUES ('admin', 'ADMIN');
INSERT IGNORE INTO ROLE_MAPPING (USERID, ROLEID) VALUES ('user', 'USER');