CREATE TABLE USERINFO (
ID NUMBER NOT NULL AUTO_INCREMENT,
USERID VARCHAR(40) UNIQUE NOT NULL, 
NAME VARCHAR(100),
PASSWORD VARCHAR(20)
);


CREATE TABLE SERVICEREQUEST (
ID NUMBER NOT NULL AUTO_INCREMENT, 
FIELD1 VARCHAR(100),
FIELD2 VARCHAR(100),
FIELD3 VARCHAR(100),
FIELD4 VARCHAR(100)
);
