CREATE TABLE IF NOT EXISTS USERINFO (
ID NUMBER NOT NULL AUTO_INCREMENT,
USERID VARCHAR(40) UNIQUE NOT NULL, 
NAME VARCHAR(100),
PASSWORD VARCHAR(20),
LOCKED BOOLEAN DEFAULT FALSE,
PASSWORD_EXPIRED BOOLEAN DEFAULT FALSE,
PRIMARY KEY(USERID)
);

CREATE TABLE IF NOT EXISTS USERROLES(
ID NUMBER NOT NULL AUTO_INCREMENT,
ROLEID VARCHAR(40) UNIQUE NOT NULL,
ROLE_NAME VARCHAR(40) UNIQUE NOT NULL,
PRIMARY KEY(ROLEID)
);

CREATE TABLE IF NOT EXISTS ROLE_MAPPING(
ID NUMBER NOT NULL AUTO_INCREMENT,
USERID VARCHAR(40) NOT NULL,
ROLEID VARCHAR(40) NOT NULL,
PRIMARY KEY(USERID, ROLEID),
FOREIGN KEY(USERID) REFERENCES USERINFO(USERID),
FOREIGN KEY(ROLEID) REFERENCES USERROLES(ROLEID)
);

CREATE TABLE IF NOT EXISTS SERVICEREQUEST (
ID NUMBER NOT NULL AUTO_INCREMENT, 
FIELD1 VARCHAR(100),
FIELD2 VARCHAR(100),
FIELD3 VARCHAR(100),
FIELD4 VARCHAR(100)
);
